server:
  port: 8761   #指定Eurka实例端口
  
spring:
  application:
    name: eureka-server  
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
    
  #instance:
    #lease-renewal-interval-in-seconds: 30
    #lease-expiration-duration-in-seconds: 90
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
      #http://discovery:8761/eureka/ ; http://discovery:8761/eureka/
  server:
    enable-self-preservation: false      
#logging:
#  level:
#    com.netflix.eureka: off
#    com.netflix.discovery: off

info:
  app.name: ${spring.application.name}
  version: v0.0.1


  